name: GitHub CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.1

      - name: Install dependent libraries
        run: sudo apt-get install libpq-dev

      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gem-

      - name: Setup app with migrations
        run: ./bin/setup
        env:
          BUNDLE_PATH: vendor/bundle
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres

      - name: Run rspec tests
        run: ./bin/rspec spec
        env:
          BUNDLE_PATH: vendor/bundle
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres
